# Generated by Django 5.2.16 on 2026-07-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StuInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField(null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
            ],
        ),
    ]
